#!/usr/bin/env php
<?php

ini_set('display_errors', 1);

require_once __DIR__ . '/../../autoload.php';

define('BASE_DIRECTORY', realpath(dirname(dirname(dirname(__DIR__)))));
define('LIQUEFY_DIRECTORY', realpath(__DIR__));
define('LIQUEFY_CWD', realpath(getcwd()));

$application = new \Symfony\Component\Console\Application();
$application->setCommandLoader(
    new \Symfony\Component\Console\CommandLoader\FactoryCommandLoader(
        [
            'render:all' => function () {
                return new \KayStrobach\Liquefy\Command\RenderCommand('render:all');
            },
            'datafile:create' => function () {
                return new \KayStrobach\Liquefy\Command\DataFileCreateCommand('datafile:create');
            },
        ]
    )
);
$application->setDefaultCommand('render:all');

try {
    $application->run();
} catch (\Exception $e) {
    // disable qa warnings
    throw new $e;
}
