#-----------------------------------------------------------------------------------------------------------------------
layout:
  brand:
    name: "liquefy by 4viewture"
    link: "https://4viewture.eu"
  logo:
    name: ""
    link: ""
    file: ""
  lazyload: true
  livereload: true

tracker:
  gitlab:
    enable: false
    name: "Gitlab"
    link:
      url: "https://gitlab.com"
      params:
        "issue[title]": "Problem with %templatefile% and %datafile"
        "issue[description]": "Please provide as much information as possible"

devices:
  vanilla-desktop-fhd:
    name: "full hd"
    enable: true
    width:  1980
    height: 1080
    scale:  0.18
  vanilla-desktop-hd-ready:
    name: "hd ready"
    enable: true
    width:  1280
    height:  720
    scale:  0.28
  apple-iphone-6s:
    name: "iPhone 6s"
    enable: true
    width:   365
    height:  667
    scale:  0.33
  apple-iphone-6s-plus:
    name: "iPhone 6s"
    enable: true
    width:   414
    height:  736
    scale:  0.38
  apple-iphone-se:
    name: "iPhone SE"
    enable: true
    width:   320
    height:  586
    scale:  0.38
  apple-ipad-air-1:
    name: "iPad Air"
    enable: true
    width:  1024
    height:  768
    scale:  0.28
  google-nexus-6:
    name: "Nexus 6"
    enable: true
    width:   412
    height:  732
    scale:  0.38

#-----------------------------------------------------------------------------------------------------------------------
#hooks:
#  preRender:
#    - npm build
#  postRender:
#    -
#-----------------------------------------------------------------------------------------------------------------------
rendering:
  #---------------------------------------------------------------------------------------------------------------------
  # Rendering of the welcome screen
  overview:
    templateFile: %liquefyPackagePath%/Resources/Private/Templates/Overview/Index.html
    layoutRootPaths:
      - %liquefyPackagePath%/Resources/Private/Layouts/
    partialRootPaths:
      - %liquefyPackagePath%/Resources/Private/Partials
  #---------------------------------------------------------------------------------------------------------------------
  # settings for the detail views
  templates:
    templatePaths:
      - %rootPath%/Resources/Private/Templates/
    layoutRootPaths:
      - %rootPath%/Resources/Private/Layouts/
    partialRootPaths:
      - %rootPath%/Resources/Private/Partials
    databagPath:
      - %rootPath%/Resources/Private/TemplatesExampleData/%controller%/%action%/
  #---------------------------------------------------------------------------------------------------------------------
  # settings for the partials which are rendered
  partials:
    templateFile: %liquefyPackagePath%/Resources/Private/Templates/Partials/Index.html
    layoutRootPaths:
      - %rootPath%/Resources/Private/Layouts/
    partialRootPaths:
      - %rootPath%/Resources/Private/Partials
    databagPath:
      - %rootPath%/Resources/Private/PartialsExampleData/%partial%/
  #---------------------------------------------------------------------------------------------------------------------
  # Allow custom viewHelpers to be loaded from external libraries
  viewHelpers:
    fluidNamespaces:
        f:
            - TYPO3\CMS\Fluid\ViewHelpers
            - KayStrobach\Liquefy\ViewHelpers
    # This is a planned feature for displaying content of non created viewHelpers
    # This is inspired by https://github.com/NamelessCoder/patternlab-fluid-patternengine/tree/master/src/Emulation
    emulatedViewHelpers:
        My\Special\TagGeneratingViewHelper:
            tagName: "a"
            attributeMap:
                specialTargetArgumentName: "href"
            outputsTagContent: true
            forceClosingTag: true
        My\Special\NormalViewHelper:
            outputsTagContent: true